import { generateId } from './utils'
import type { Workspace, Board } from '@/types'

export function createDefaultWorkspace(): Workspace {
  return {
    id: generateId(),
    name: 'My Workspace',
    description: 'Your personal workspace',
    boards: [],
    members: [
      {
        id: generateId(),
        workspaceId: '',
        userId: 'user_1',
        role: 'owner',
        joinedAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
}

export function createDemoBoard(workspaceId: string): Board {
  const boardId = generateId()
  const rootId = generateId()
  const child1Id = generateId()
  const child2Id = generateId()
  const child3Id = generateId()
  const sub1Id = generateId()
  const sub2Id = generateId()

  return {
    id: boardId,
    workspaceId,
    title: 'Getting Started Mind Map',
    description: 'A sample mind map to get started',
    viewport: { x: 0, y: 0, zoom: 1 },
    nodes: [
      {
        id: rootId,
        boardId,
        parentId: null,
        title: 'Welcome to MindFlow',
        description: 'Your infinite whiteboard for mind mapping and visual planning',
        emoji: '🚀',
        icon: null,
        color: '#4F46E5',
        shape: 'roundedRectangle',
        collapsed: false,
        locked: false,
        x: 500,
        y: 300,
        width: 220,
        height: 120,
        rotation: 0,
        zIndex: 0,
        tags: ['welcome'],
        metadata: {},
      },
      {
        id: child1Id,
        boardId,
        parentId: rootId,
        title: 'Create Nodes',
        description: 'Double-click canvas or press N to create a new node',
        emoji: '💡',
        icon: null,
        color: '#22C55E',
        shape: 'roundedRectangle',
        collapsed: false,
        locked: false,
        x: 800,
        y: 200,
        width: 200,
        height: 100,
        rotation: 0,
        zIndex: 1,
        tags: ['basics'],
        metadata: {},
      },
      {
        id: child2Id,
        boardId,
        parentId: rootId,
        title: 'Organize Ideas',
        description: 'Drag to connect nodes, use Tab for child nodes',
        emoji: '🔗',
        icon: null,
        color: '#F97316',
        shape: 'roundedRectangle',
        collapsed: false,
        locked: false,
        x: 800,
        y: 350,
        width: 200,
        height: 100,
        rotation: 0,
        zIndex: 2,
        tags: ['organization'],
        metadata: {},
      },
      {
        id: child3Id,
        boardId,
        parentId: rootId,
        title: 'Collaborate',
        description: 'Share your board and work together in real-time',
        emoji: '👥',
        icon: null,
        color: '#3B82F6',
        shape: 'roundedRectangle',
        collapsed: false,
        locked: false,
        x: 800,
        y: 500,
        width: 200,
        height: 100,
        rotation: 0,
        zIndex: 3,
        tags: ['collaboration'],
        metadata: {},
      },
      {
        id: sub1Id,
        boardId,
        parentId: child1Id,
        title: 'Keyboard Shortcuts',
        description: 'N: New, Tab: Child, Enter: Sibling',
        emoji: '⌨️',
        icon: null,
        color: '#6366F1',
        shape: 'stickyNote',
        collapsed: false,
        locked: false,
        x: 1080,
        y: 170,
        width: 180,
        height: 80,
        rotation: 0,
        zIndex: 4,
        tags: ['shortcuts', 'tips'],
        metadata: {},
      },
      {
        id: sub2Id,
        boardId,
        parentId: child1Id,
        title: 'Different Shapes',
        description: 'Try circle, diamond, hexagon, and more',
        emoji: '⬡',
        icon: null,
        color: '#EC4899',
        shape: 'diamond',
        collapsed: false,
        locked: false,
        x: 1080,
        y: 290,
        width: 180,
        height: 100,
        rotation: 0,
        zIndex: 5,
        tags: ['shapes'],
        metadata: {},
      },
    ],
    edges: [
      { id: generateId(), boardId, sourceId: rootId, targetId: child1Id, type: 'bezier', style: 'solid', arrowEnd: true, arrowStart: false, label: '', color: '#94a3b8', animated: false, metadata: {} },
      { id: generateId(), boardId, sourceId: rootId, targetId: child2Id, type: 'bezier', style: 'solid', arrowEnd: true, arrowStart: false, label: '', color: '#94a3b8', animated: false, metadata: {} },
      { id: generateId(), boardId, sourceId: rootId, targetId: child3Id, type: 'bezier', style: 'solid', arrowEnd: true, arrowStart: false, label: '', color: '#94a3b8', animated: false, metadata: {} },
      { id: generateId(), boardId, sourceId: child1Id, targetId: sub1Id, type: 'bezier', style: 'dashed', arrowEnd: true, arrowStart: false, label: '', color: '#94a3b8', animated: false, metadata: {} },
      { id: generateId(), boardId, sourceId: child1Id, targetId: sub2Id, type: 'bezier', style: 'dashed', arrowEnd: true, arrowStart: false, label: '', color: '#94a3b8', animated: false, metadata: {} },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
}
